"""empty message

Revision ID: 75573044ab9b
Revises: 4d2f5aba4925
Create Date: 2020-04-08 06:11:39.468029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75573044ab9b'
down_revision = '4d2f5aba4925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
